spring:
  #服务名称
  application:
    name: eureka-server
  #json序列化
  jackson:
      deserialization: true
#端口
server:
  port: 1111
eureka:
  #主页
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  client:
      service-url:
        defaultZone: http://waterlufei:123456@localhost:1111/eureka/
        #注册，防止自我注册
        #register-with-eureka: false
        #fetch-registry: false
  server:
    enable-self-preservation: false
#允许信息被监控
management:
  security:
    enabled: false
#开启安全验证
security:
  user:
    name: waterlufei
    password: 123456
logging:
  file: ./target/test.log